/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.taproot.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AccountNote service. Represents a row in the &quot;Koroneiki_AccountNote&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.taproot.model.impl.AccountNoteModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.taproot.model.impl.AccountNoteImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AccountNote
 * @generated
 */
@ProviderType
public interface AccountNoteModel
	extends BaseModel<AccountNote>, MVCCModel, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a account note model instance should use the {@link AccountNote} interface instead.
	 */

	/**
	 * Returns the primary key of this account note.
	 *
	 * @return the primary key of this account note
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this account note.
	 *
	 * @param primaryKey the primary key of this account note
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this account note.
	 *
	 * @return the mvcc version of this account note
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this account note.
	 *
	 * @param mvccVersion the mvcc version of this account note
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this account note.
	 *
	 * @return the uuid of this account note
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this account note.
	 *
	 * @param uuid the uuid of this account note
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the account note ID of this account note.
	 *
	 * @return the account note ID of this account note
	 */
	public long getAccountNoteId();

	/**
	 * Sets the account note ID of this account note.
	 *
	 * @param accountNoteId the account note ID of this account note
	 */
	public void setAccountNoteId(long accountNoteId);

	/**
	 * Returns the company ID of this account note.
	 *
	 * @return the company ID of this account note
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this account note.
	 *
	 * @param companyId the company ID of this account note
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this account note.
	 *
	 * @return the user ID of this account note
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this account note.
	 *
	 * @param userId the user ID of this account note
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this account note.
	 *
	 * @return the user uuid of this account note
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this account note.
	 *
	 * @param userUuid the user uuid of this account note
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this account note.
	 *
	 * @return the create date of this account note
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this account note.
	 *
	 * @param createDate the create date of this account note
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the creator uid of this account note.
	 *
	 * @return the creator uid of this account note
	 */
	@AutoEscape
	public String getCreatorUID();

	/**
	 * Sets the creator uid of this account note.
	 *
	 * @param creatorUID the creator uid of this account note
	 */
	public void setCreatorUID(String creatorUID);

	/**
	 * Returns the creator name of this account note.
	 *
	 * @return the creator name of this account note
	 */
	@AutoEscape
	public String getCreatorName();

	/**
	 * Sets the creator name of this account note.
	 *
	 * @param creatorName the creator name of this account note
	 */
	public void setCreatorName(String creatorName);

	/**
	 * Returns the modified date of this account note.
	 *
	 * @return the modified date of this account note
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this account note.
	 *
	 * @param modifiedDate the modified date of this account note
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modifier uid of this account note.
	 *
	 * @return the modifier uid of this account note
	 */
	@AutoEscape
	public String getModifierUID();

	/**
	 * Sets the modifier uid of this account note.
	 *
	 * @param modifierUID the modifier uid of this account note
	 */
	public void setModifierUID(String modifierUID);

	/**
	 * Returns the modifier name of this account note.
	 *
	 * @return the modifier name of this account note
	 */
	@AutoEscape
	public String getModifierName();

	/**
	 * Sets the modifier name of this account note.
	 *
	 * @param modifierName the modifier name of this account note
	 */
	public void setModifierName(String modifierName);

	/**
	 * Returns the account note key of this account note.
	 *
	 * @return the account note key of this account note
	 */
	@AutoEscape
	public String getAccountNoteKey();

	/**
	 * Sets the account note key of this account note.
	 *
	 * @param accountNoteKey the account note key of this account note
	 */
	public void setAccountNoteKey(String accountNoteKey);

	/**
	 * Returns the account ID of this account note.
	 *
	 * @return the account ID of this account note
	 */
	public long getAccountId();

	/**
	 * Sets the account ID of this account note.
	 *
	 * @param accountId the account ID of this account note
	 */
	public void setAccountId(long accountId);

	/**
	 * Returns the type of this account note.
	 *
	 * @return the type of this account note
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this account note.
	 *
	 * @param type the type of this account note
	 */
	public void setType(String type);

	/**
	 * Returns the priority of this account note.
	 *
	 * @return the priority of this account note
	 */
	public int getPriority();

	/**
	 * Sets the priority of this account note.
	 *
	 * @param priority the priority of this account note
	 */
	public void setPriority(int priority);

	/**
	 * Returns the content of this account note.
	 *
	 * @return the content of this account note
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this account note.
	 *
	 * @param content the content of this account note
	 */
	public void setContent(String content);

	/**
	 * Returns the format of this account note.
	 *
	 * @return the format of this account note
	 */
	@AutoEscape
	public String getFormat();

	/**
	 * Sets the format of this account note.
	 *
	 * @param format the format of this account note
	 */
	public void setFormat(String format);

	/**
	 * Returns the status of this account note.
	 *
	 * @return the status of this account note
	 */
	@AutoEscape
	public String getStatus();

	/**
	 * Sets the status of this account note.
	 *
	 * @param status the status of this account note
	 */
	public void setStatus(String status);

}