/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.taproot.model;

import com.liferay.osb.koroneiki.taproot.service.persistence.TeamProjectRolePK;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TeamProjectRole service. Represents a row in the &quot;Koroneiki_TeamProjectRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.taproot.model.impl.TeamProjectRoleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.taproot.model.impl.TeamProjectRoleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeamProjectRole
 * @generated
 */
@ProviderType
public interface TeamProjectRoleModel extends BaseModel<TeamProjectRole> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team project role model instance should use the {@link TeamProjectRole} interface instead.
	 */

	/**
	 * Returns the primary key of this team project role.
	 *
	 * @return the primary key of this team project role
	 */
	public TeamProjectRolePK getPrimaryKey();

	/**
	 * Sets the primary key of this team project role.
	 *
	 * @param primaryKey the primary key of this team project role
	 */
	public void setPrimaryKey(TeamProjectRolePK primaryKey);

	/**
	 * Returns the team ID of this team project role.
	 *
	 * @return the team ID of this team project role
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this team project role.
	 *
	 * @param teamId the team ID of this team project role
	 */
	public void setTeamId(long teamId);

	/**
	 * Returns the project ID of this team project role.
	 *
	 * @return the project ID of this team project role
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this team project role.
	 *
	 * @param projectId the project ID of this team project role
	 */
	public void setProjectId(long projectId);

	/**
	 * Returns the team role ID of this team project role.
	 *
	 * @return the team role ID of this team project role
	 */
	public long getTeamRoleId();

	/**
	 * Sets the team role ID of this team project role.
	 *
	 * @param teamRoleId the team role ID of this team project role
	 */
	public void setTeamRoleId(long teamRoleId);

}