/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.taproot.model;

import com.liferay.osb.koroneiki.taproot.service.persistence.TeamProjectPK;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the TeamProject service. Represents a row in the &quot;Koroneiki_TeamProject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.taproot.model.impl.TeamProjectModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.taproot.model.impl.TeamProjectImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TeamProject
 * @generated
 */
@ProviderType
public interface TeamProjectModel extends BaseModel<TeamProject> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a team project model instance should use the {@link TeamProject} interface instead.
	 */

	/**
	 * Returns the primary key of this team project.
	 *
	 * @return the primary key of this team project
	 */
	public TeamProjectPK getPrimaryKey();

	/**
	 * Sets the primary key of this team project.
	 *
	 * @param primaryKey the primary key of this team project
	 */
	public void setPrimaryKey(TeamProjectPK primaryKey);

	/**
	 * Returns the team ID of this team project.
	 *
	 * @return the team ID of this team project
	 */
	public long getTeamId();

	/**
	 * Sets the team ID of this team project.
	 *
	 * @param teamId the team ID of this team project
	 */
	public void setTeamId(long teamId);

	/**
	 * Returns the project ID of this team project.
	 *
	 * @return the project ID of this team project
	 */
	public long getProjectId();

	/**
	 * Sets the project ID of this team project.
	 *
	 * @param projectId the project ID of this team project
	 */
	public void setProjectId(long projectId);

}