/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.provisioning.model.impl;

import com.liferay.osb.provisioning.model.ProductBundleProductEntries;
import com.liferay.osb.provisioning.model.ProductBundleProductEntriesModel;
import com.liferay.osb.provisioning.service.persistence.ProductBundleProductEntriesPK;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the ProductBundleProductEntries service. Represents a row in the &quot;Provisioning_ProductBundleProductEntries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProductBundleProductEntriesModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductBundleProductEntriesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductBundleProductEntriesImpl
 * @generated
 */
public class ProductBundleProductEntriesModelImpl
	extends BaseModelImpl<ProductBundleProductEntries>
	implements ProductBundleProductEntriesModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product bundle product entries model instance should use the <code>ProductBundleProductEntries</code> interface instead.
	 */
	public static final String TABLE_NAME =
		"Provisioning_ProductBundleProductEntries";

	public static final Object[][] TABLE_COLUMNS = {
		{"mvccVersion", Types.BIGINT}, {"productBundleId", Types.BIGINT},
		{"productEntryId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("mvccVersion", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productBundleId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("productEntryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table Provisioning_ProductBundleProductEntries (mvccVersion LONG default 0 not null,productBundleId LONG not null,productEntryId LONG not null,primary key (productBundleId, productEntryId))";

	public static final String TABLE_SQL_DROP =
		"drop table Provisioning_ProductBundleProductEntries";

	public static final String ORDER_BY_JPQL =
		" ORDER BY productBundleProductEntries.id.productBundleId ASC, productBundleProductEntries.id.productEntryId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY Provisioning_ProductBundleProductEntries.productBundleId ASC, Provisioning_ProductBundleProductEntries.productEntryId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long PRODUCTBUNDLEID_COLUMN_BITMASK = 1L;

	public static final long PRODUCTENTRYID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public ProductBundleProductEntriesModelImpl() {
	}

	@Override
	public ProductBundleProductEntriesPK getPrimaryKey() {
		return new ProductBundleProductEntriesPK(
			_productBundleId, _productEntryId);
	}

	@Override
	public void setPrimaryKey(ProductBundleProductEntriesPK primaryKey) {
		setProductBundleId(primaryKey.productBundleId);
		setProductEntryId(primaryKey.productEntryId);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ProductBundleProductEntriesPK(
			_productBundleId, _productEntryId);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ProductBundleProductEntriesPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ProductBundleProductEntries.class;
	}

	@Override
	public String getModelClassName() {
		return ProductBundleProductEntries.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProductBundleProductEntries, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProductBundleProductEntries, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductBundleProductEntries, Object>
				attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply(
					(ProductBundleProductEntries)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProductBundleProductEntries, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProductBundleProductEntries, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProductBundleProductEntries)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProductBundleProductEntries, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProductBundleProductEntries, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, ProductBundleProductEntries>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			ProductBundleProductEntries.class.getClassLoader(),
			ProductBundleProductEntries.class, ModelWrapper.class);

		try {
			Constructor<ProductBundleProductEntries> constructor =
				(Constructor<ProductBundleProductEntries>)
					proxyClass.getConstructor(InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map
		<String, Function<ProductBundleProductEntries, Object>>
			_attributeGetterFunctions;
	private static final Map
		<String, BiConsumer<ProductBundleProductEntries, Object>>
			_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProductBundleProductEntries, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProductBundleProductEntries, Object>>();
		Map<String, BiConsumer<ProductBundleProductEntries, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<ProductBundleProductEntries, ?>>();

		attributeGetterFunctions.put(
			"mvccVersion", ProductBundleProductEntries::getMvccVersion);
		attributeSetterBiConsumers.put(
			"mvccVersion",
			(BiConsumer<ProductBundleProductEntries, Long>)
				ProductBundleProductEntries::setMvccVersion);
		attributeGetterFunctions.put(
			"productBundleId", ProductBundleProductEntries::getProductBundleId);
		attributeSetterBiConsumers.put(
			"productBundleId",
			(BiConsumer<ProductBundleProductEntries, Long>)
				ProductBundleProductEntries::setProductBundleId);
		attributeGetterFunctions.put(
			"productEntryId", ProductBundleProductEntries::getProductEntryId);
		attributeSetterBiConsumers.put(
			"productEntryId",
			(BiConsumer<ProductBundleProductEntries, Long>)
				ProductBundleProductEntries::setProductEntryId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getMvccVersion() {
		return _mvccVersion;
	}

	@Override
	public void setMvccVersion(long mvccVersion) {
		_mvccVersion = mvccVersion;
	}

	@Override
	public long getProductBundleId() {
		return _productBundleId;
	}

	@Override
	public void setProductBundleId(long productBundleId) {
		_columnBitmask |= PRODUCTBUNDLEID_COLUMN_BITMASK;

		if (!_setOriginalProductBundleId) {
			_setOriginalProductBundleId = true;

			_originalProductBundleId = _productBundleId;
		}

		_productBundleId = productBundleId;
	}

	public long getOriginalProductBundleId() {
		return _originalProductBundleId;
	}

	@Override
	public long getProductEntryId() {
		return _productEntryId;
	}

	@Override
	public void setProductEntryId(long productEntryId) {
		_productEntryId = productEntryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ProductBundleProductEntries toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProductBundleProductEntries>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProductBundleProductEntriesImpl productBundleProductEntriesImpl =
			new ProductBundleProductEntriesImpl();

		productBundleProductEntriesImpl.setMvccVersion(getMvccVersion());
		productBundleProductEntriesImpl.setProductBundleId(
			getProductBundleId());
		productBundleProductEntriesImpl.setProductEntryId(getProductEntryId());

		productBundleProductEntriesImpl.resetOriginalValues();

		return productBundleProductEntriesImpl;
	}

	@Override
	public int compareTo(
		ProductBundleProductEntries productBundleProductEntries) {

		ProductBundleProductEntriesPK primaryKey =
			productBundleProductEntries.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProductBundleProductEntries)) {
			return false;
		}

		ProductBundleProductEntries productBundleProductEntries =
			(ProductBundleProductEntries)object;

		ProductBundleProductEntriesPK primaryKey =
			productBundleProductEntries.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		ProductBundleProductEntriesModelImpl
			productBundleProductEntriesModelImpl = this;

		productBundleProductEntriesModelImpl._originalProductBundleId =
			productBundleProductEntriesModelImpl._productBundleId;

		productBundleProductEntriesModelImpl._setOriginalProductBundleId =
			false;

		productBundleProductEntriesModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<ProductBundleProductEntries> toCacheModel() {
		ProductBundleProductEntriesCacheModel
			productBundleProductEntriesCacheModel =
				new ProductBundleProductEntriesCacheModel();

		productBundleProductEntriesCacheModel.productBundleProductEntriesPK =
			getPrimaryKey();

		productBundleProductEntriesCacheModel.mvccVersion = getMvccVersion();

		productBundleProductEntriesCacheModel.productBundleId =
			getProductBundleId();

		productBundleProductEntriesCacheModel.productEntryId =
			getProductEntryId();

		return productBundleProductEntriesCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProductBundleProductEntries, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProductBundleProductEntries, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductBundleProductEntries, Object>
				attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply(
					(ProductBundleProductEntries)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ProductBundleProductEntries, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ProductBundleProductEntries, Object>>
				entry : attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProductBundleProductEntries, Object>
				attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply(
					(ProductBundleProductEntries)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function
			<InvocationHandler, ProductBundleProductEntries>
				_escapedModelProxyProviderFunction =
					_getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _mvccVersion;
	private long _productBundleId;
	private long _originalProductBundleId;
	private boolean _setOriginalProductBundleId;
	private long _productEntryId;
	private long _columnBitmask;
	private ProductBundleProductEntries _escapedModel;

}