/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.provisioning.model.impl;

import com.liferay.osb.provisioning.model.ProductBundleProductEntries;
import com.liferay.osb.provisioning.service.ProductBundleProductEntriesLocalServiceUtil;

/**
 * The extended model base implementation for the ProductBundleProductEntries service. Represents a row in the &quot;Provisioning_ProductBundleProductEntries&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProductBundleProductEntriesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductBundleProductEntriesImpl
 * @see ProductBundleProductEntries
 * @generated
 */
public abstract class ProductBundleProductEntriesBaseImpl
	extends ProductBundleProductEntriesModelImpl
	implements ProductBundleProductEntries {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a product bundle product entries model instance should use the <code>ProductBundleProductEntries</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			ProductBundleProductEntriesLocalServiceUtil.
				addProductBundleProductEntries(this);
		}
		else {
			ProductBundleProductEntriesLocalServiceUtil.
				updateProductBundleProductEntries(this);
		}
	}

}