/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.phytohormone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.AttachedModel;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Entitlement service. Represents a row in the &quot;Koroneiki_Entitlement&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.phytohormone.model.impl.EntitlementModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.phytohormone.model.impl.EntitlementImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Entitlement
 * @generated
 */
@ProviderType
public interface EntitlementModel
	extends AttachedModel, BaseModel<Entitlement>, MVCCModel, ShardedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a entitlement model instance should use the {@link Entitlement} interface instead.
	 */

	/**
	 * Returns the primary key of this entitlement.
	 *
	 * @return the primary key of this entitlement
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this entitlement.
	 *
	 * @param primaryKey the primary key of this entitlement
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this entitlement.
	 *
	 * @return the mvcc version of this entitlement
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this entitlement.
	 *
	 * @param mvccVersion the mvcc version of this entitlement
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the entitlement ID of this entitlement.
	 *
	 * @return the entitlement ID of this entitlement
	 */
	public long getEntitlementId();

	/**
	 * Sets the entitlement ID of this entitlement.
	 *
	 * @param entitlementId the entitlement ID of this entitlement
	 */
	public void setEntitlementId(long entitlementId);

	/**
	 * Returns the company ID of this entitlement.
	 *
	 * @return the company ID of this entitlement
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this entitlement.
	 *
	 * @param companyId the company ID of this entitlement
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this entitlement.
	 *
	 * @return the user ID of this entitlement
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this entitlement.
	 *
	 * @param userId the user ID of this entitlement
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this entitlement.
	 *
	 * @return the user uuid of this entitlement
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this entitlement.
	 *
	 * @param userUuid the user uuid of this entitlement
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this entitlement.
	 *
	 * @return the create date of this entitlement
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this entitlement.
	 *
	 * @param createDate the create date of this entitlement
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this entitlement.
	 *
	 * @return the modified date of this entitlement
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this entitlement.
	 *
	 * @param modifiedDate the modified date of this entitlement
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the entitlement definition ID of this entitlement.
	 *
	 * @return the entitlement definition ID of this entitlement
	 */
	public long getEntitlementDefinitionId();

	/**
	 * Sets the entitlement definition ID of this entitlement.
	 *
	 * @param entitlementDefinitionId the entitlement definition ID of this entitlement
	 */
	public void setEntitlementDefinitionId(long entitlementDefinitionId);

	/**
	 * Returns the fully qualified class name of this entitlement.
	 *
	 * @return the fully qualified class name of this entitlement
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this entitlement.
	 *
	 * @return the class name ID of this entitlement
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this entitlement.
	 *
	 * @param classNameId the class name ID of this entitlement
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the class pk of this entitlement.
	 *
	 * @return the class pk of this entitlement
	 */
	@Override
	public long getClassPK();

	/**
	 * Sets the class pk of this entitlement.
	 *
	 * @param classPK the class pk of this entitlement
	 */
	@Override
	public void setClassPK(long classPK);

	/**
	 * Returns the name of this entitlement.
	 *
	 * @return the name of this entitlement
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this entitlement.
	 *
	 * @param name the name of this entitlement
	 */
	public void setName(String name);

}