/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.koroneiki.phytohormone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;
import com.liferay.portal.kernel.model.TypedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the EntitlementDefinition service. Represents a row in the &quot;Koroneiki_EntitlementDefinition&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.koroneiki.phytohormone.model.impl.EntitlementDefinitionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.koroneiki.phytohormone.model.impl.EntitlementDefinitionImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EntitlementDefinition
 * @generated
 */
@ProviderType
public interface EntitlementDefinitionModel
	extends BaseModel<EntitlementDefinition>, ShardedModel, StagedModel,
			TypedModel {

	/**
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a entitlement definition model instance should use the {@link EntitlementDefinition} interface instead.
	 */

	/**
	 * Returns the primary key of this entitlement definition.
	 *
	 * @return the primary key of this entitlement definition
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this entitlement definition.
	 *
	 * @param primaryKey the primary key of this entitlement definition
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this entitlement definition.
	 *
	 * @return the uuid of this entitlement definition
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this entitlement definition.
	 *
	 * @param uuid the uuid of this entitlement definition
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the entitlement definition ID of this entitlement definition.
	 *
	 * @return the entitlement definition ID of this entitlement definition
	 */
	public long getEntitlementDefinitionId();

	/**
	 * Sets the entitlement definition ID of this entitlement definition.
	 *
	 * @param entitlementDefinitionId the entitlement definition ID of this entitlement definition
	 */
	public void setEntitlementDefinitionId(long entitlementDefinitionId);

	/**
	 * Returns the company ID of this entitlement definition.
	 *
	 * @return the company ID of this entitlement definition
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this entitlement definition.
	 *
	 * @param companyId the company ID of this entitlement definition
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this entitlement definition.
	 *
	 * @return the user ID of this entitlement definition
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this entitlement definition.
	 *
	 * @param userId the user ID of this entitlement definition
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this entitlement definition.
	 *
	 * @return the user uuid of this entitlement definition
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this entitlement definition.
	 *
	 * @param userUuid the user uuid of this entitlement definition
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this entitlement definition.
	 *
	 * @return the create date of this entitlement definition
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this entitlement definition.
	 *
	 * @param createDate the create date of this entitlement definition
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this entitlement definition.
	 *
	 * @return the modified date of this entitlement definition
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this entitlement definition.
	 *
	 * @param modifiedDate the modified date of this entitlement definition
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the entitlement definition key of this entitlement definition.
	 *
	 * @return the entitlement definition key of this entitlement definition
	 */
	@AutoEscape
	public String getEntitlementDefinitionKey();

	/**
	 * Sets the entitlement definition key of this entitlement definition.
	 *
	 * @param entitlementDefinitionKey the entitlement definition key of this entitlement definition
	 */
	public void setEntitlementDefinitionKey(String entitlementDefinitionKey);

	/**
	 * Returns the fully qualified class name of this entitlement definition.
	 *
	 * @return the fully qualified class name of this entitlement definition
	 */
	@Override
	public String getClassName();

	public void setClassName(String className);

	/**
	 * Returns the class name ID of this entitlement definition.
	 *
	 * @return the class name ID of this entitlement definition
	 */
	@Override
	public long getClassNameId();

	/**
	 * Sets the class name ID of this entitlement definition.
	 *
	 * @param classNameId the class name ID of this entitlement definition
	 */
	@Override
	public void setClassNameId(long classNameId);

	/**
	 * Returns the name of this entitlement definition.
	 *
	 * @return the name of this entitlement definition
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this entitlement definition.
	 *
	 * @param name the name of this entitlement definition
	 */
	public void setName(String name);

	/**
	 * Returns the description of this entitlement definition.
	 *
	 * @return the description of this entitlement definition
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this entitlement definition.
	 *
	 * @param description the description of this entitlement definition
	 */
	public void setDescription(String description);

	/**
	 * Returns the definition of this entitlement definition.
	 *
	 * @return the definition of this entitlement definition
	 */
	@AutoEscape
	public String getDefinition();

	/**
	 * Sets the definition of this entitlement definition.
	 *
	 * @param definition the definition of this entitlement definition
	 */
	public void setDefinition(String definition);

	/**
	 * Returns the status of this entitlement definition.
	 *
	 * @return the status of this entitlement definition
	 */
	public int getStatus();

	/**
	 * Sets the status of this entitlement definition.
	 *
	 * @param status the status of this entitlement definition
	 */
	public void setStatus(int status);

}