/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.provisioning.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductBundle service. Represents a row in the &quot;Provisioning_ProductBundle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.provisioning.model.impl.ProductBundleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.provisioning.model.impl.ProductBundleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductBundle
 * @generated
 */
@ProviderType
public interface ProductBundleModel
	extends BaseModel<ProductBundle>, MVCCModel, ShardedModel, StagedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product bundle model instance should use the {@link ProductBundle} interface instead.
	 */

	/**
	 * Returns the primary key of this product bundle.
	 *
	 * @return the primary key of this product bundle
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this product bundle.
	 *
	 * @param primaryKey the primary key of this product bundle
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the mvcc version of this product bundle.
	 *
	 * @return the mvcc version of this product bundle
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this product bundle.
	 *
	 * @param mvccVersion the mvcc version of this product bundle
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the uuid of this product bundle.
	 *
	 * @return the uuid of this product bundle
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this product bundle.
	 *
	 * @param uuid the uuid of this product bundle
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the product bundle ID of this product bundle.
	 *
	 * @return the product bundle ID of this product bundle
	 */
	public long getProductBundleId();

	/**
	 * Sets the product bundle ID of this product bundle.
	 *
	 * @param productBundleId the product bundle ID of this product bundle
	 */
	public void setProductBundleId(long productBundleId);

	/**
	 * Returns the company ID of this product bundle.
	 *
	 * @return the company ID of this product bundle
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this product bundle.
	 *
	 * @param companyId the company ID of this product bundle
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this product bundle.
	 *
	 * @return the user ID of this product bundle
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this product bundle.
	 *
	 * @param userId the user ID of this product bundle
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this product bundle.
	 *
	 * @return the user uuid of this product bundle
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this product bundle.
	 *
	 * @param userUuid the user uuid of this product bundle
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this product bundle.
	 *
	 * @return the create date of this product bundle
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this product bundle.
	 *
	 * @param createDate the create date of this product bundle
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this product bundle.
	 *
	 * @return the modified date of this product bundle
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this product bundle.
	 *
	 * @param modifiedDate the modified date of this product bundle
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the name of this product bundle.
	 *
	 * @return the name of this product bundle
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this product bundle.
	 *
	 * @param name the name of this product bundle
	 */
	public void setName(String name);

}