/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.provisioning.model;

import com.liferay.osb.provisioning.service.persistence.ProductBundleProductsPK;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.MVCCModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProductBundleProducts service. Represents a row in the &quot;Provisioning_ProductBundleProducts&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.osb.provisioning.model.impl.ProductBundleProductsModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.osb.provisioning.model.impl.ProductBundleProductsImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProductBundleProducts
 * @generated
 */
@ProviderType
public interface ProductBundleProductsModel
	extends BaseModel<ProductBundleProducts>, MVCCModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a product bundle products model instance should use the {@link ProductBundleProducts} interface instead.
	 */

	/**
	 * Returns the primary key of this product bundle products.
	 *
	 * @return the primary key of this product bundle products
	 */
	public ProductBundleProductsPK getPrimaryKey();

	/**
	 * Sets the primary key of this product bundle products.
	 *
	 * @param primaryKey the primary key of this product bundle products
	 */
	public void setPrimaryKey(ProductBundleProductsPK primaryKey);

	/**
	 * Returns the mvcc version of this product bundle products.
	 *
	 * @return the mvcc version of this product bundle products
	 */
	@Override
	public long getMvccVersion();

	/**
	 * Sets the mvcc version of this product bundle products.
	 *
	 * @param mvccVersion the mvcc version of this product bundle products
	 */
	@Override
	public void setMvccVersion(long mvccVersion);

	/**
	 * Returns the product bundle ID of this product bundle products.
	 *
	 * @return the product bundle ID of this product bundle products
	 */
	public long getProductBundleId();

	/**
	 * Sets the product bundle ID of this product bundle products.
	 *
	 * @param productBundleId the product bundle ID of this product bundle products
	 */
	public void setProductBundleId(long productBundleId);

	/**
	 * Returns the product key of this product bundle products.
	 *
	 * @return the product key of this product bundle products
	 */
	@AutoEscape
	public String getProductKey();

	/**
	 * Sets the product key of this product bundle products.
	 *
	 * @param productKey the product key of this product bundle products
	 */
	public void setProductKey(String productKey);

}