/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.liferay.osb.provisioning.service.base;

import com.liferay.osb.provisioning.model.ProductBundleProductEntries;
import com.liferay.osb.provisioning.service.ProductBundleProductEntriesLocalService;
import com.liferay.osb.provisioning.service.persistence.ProductBundlePersistence;
import com.liferay.osb.provisioning.service.persistence.ProductBundleProductEntriesPK;
import com.liferay.osb.provisioning.service.persistence.ProductBundleProductEntriesPersistence;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the product bundle product entries local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.osb.provisioning.service.impl.ProductBundleProductEntriesLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.osb.provisioning.service.impl.ProductBundleProductEntriesLocalServiceImpl
 * @generated
 */
public abstract class ProductBundleProductEntriesLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   ProductBundleProductEntriesLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ProductBundleProductEntriesLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.osb.provisioning.service.ProductBundleProductEntriesLocalServiceUtil</code>.
	 */

	/**
	 * Adds the product bundle product entries to the database. Also notifies the appropriate model listeners.
	 *
	 * @param productBundleProductEntries the product bundle product entries
	 * @return the product bundle product entries that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ProductBundleProductEntries addProductBundleProductEntries(
		ProductBundleProductEntries productBundleProductEntries) {

		productBundleProductEntries.setNew(true);

		return productBundleProductEntriesPersistence.update(
			productBundleProductEntries);
	}

	/**
	 * Creates a new product bundle product entries with the primary key. Does not add the product bundle product entries to the database.
	 *
	 * @param productBundleProductEntriesPK the primary key for the new product bundle product entries
	 * @return the new product bundle product entries
	 */
	@Override
	@Transactional(enabled = false)
	public ProductBundleProductEntries createProductBundleProductEntries(
		ProductBundleProductEntriesPK productBundleProductEntriesPK) {

		return productBundleProductEntriesPersistence.create(
			productBundleProductEntriesPK);
	}

	/**
	 * Deletes the product bundle product entries with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param productBundleProductEntriesPK the primary key of the product bundle product entries
	 * @return the product bundle product entries that was removed
	 * @throws PortalException if a product bundle product entries with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ProductBundleProductEntries deleteProductBundleProductEntries(
			ProductBundleProductEntriesPK productBundleProductEntriesPK)
		throws PortalException {

		return productBundleProductEntriesPersistence.remove(
			productBundleProductEntriesPK);
	}

	/**
	 * Deletes the product bundle product entries from the database. Also notifies the appropriate model listeners.
	 *
	 * @param productBundleProductEntries the product bundle product entries
	 * @return the product bundle product entries that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ProductBundleProductEntries deleteProductBundleProductEntries(
		ProductBundleProductEntries productBundleProductEntries) {

		return productBundleProductEntriesPersistence.remove(
			productBundleProductEntries);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ProductBundleProductEntries.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return productBundleProductEntriesPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.provisioning.model.impl.ProductBundleProductEntriesModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return productBundleProductEntriesPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.provisioning.model.impl.ProductBundleProductEntriesModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return productBundleProductEntriesPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return productBundleProductEntriesPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return productBundleProductEntriesPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ProductBundleProductEntries fetchProductBundleProductEntries(
		ProductBundleProductEntriesPK productBundleProductEntriesPK) {

		return productBundleProductEntriesPersistence.fetchByPrimaryKey(
			productBundleProductEntriesPK);
	}

	/**
	 * Returns the product bundle product entries with the primary key.
	 *
	 * @param productBundleProductEntriesPK the primary key of the product bundle product entries
	 * @return the product bundle product entries
	 * @throws PortalException if a product bundle product entries with the primary key could not be found
	 */
	@Override
	public ProductBundleProductEntries getProductBundleProductEntries(
			ProductBundleProductEntriesPK productBundleProductEntriesPK)
		throws PortalException {

		return productBundleProductEntriesPersistence.findByPrimaryKey(
			productBundleProductEntriesPK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			productBundleProductEntriesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ProductBundleProductEntries.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.productBundleId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			productBundleProductEntriesLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			ProductBundleProductEntries.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.productBundleId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			productBundleProductEntriesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ProductBundleProductEntries.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.productBundleId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return productBundleProductEntriesLocalService.
			deleteProductBundleProductEntries(
				(ProductBundleProductEntries)persistedModel);
	}

	public BasePersistence<ProductBundleProductEntries> getBasePersistence() {
		return productBundleProductEntriesPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return productBundleProductEntriesPersistence.findByPrimaryKey(
			primaryKeyObj);
	}

	/**
	 * Returns a range of all the product bundle product entrieses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.osb.provisioning.model.impl.ProductBundleProductEntriesModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of product bundle product entrieses
	 * @param end the upper bound of the range of product bundle product entrieses (not inclusive)
	 * @return the range of product bundle product entrieses
	 */
	@Override
	public List<ProductBundleProductEntries> getProductBundleProductEntrieses(
		int start, int end) {

		return productBundleProductEntriesPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of product bundle product entrieses.
	 *
	 * @return the number of product bundle product entrieses
	 */
	@Override
	public int getProductBundleProductEntriesesCount() {
		return productBundleProductEntriesPersistence.countAll();
	}

	/**
	 * Updates the product bundle product entries in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param productBundleProductEntries the product bundle product entries
	 * @return the product bundle product entries that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ProductBundleProductEntries updateProductBundleProductEntries(
		ProductBundleProductEntries productBundleProductEntries) {

		return productBundleProductEntriesPersistence.update(
			productBundleProductEntries);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ProductBundleProductEntriesLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		productBundleProductEntriesLocalService =
			(ProductBundleProductEntriesLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ProductBundleProductEntriesLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ProductBundleProductEntries.class;
	}

	protected String getModelClassName() {
		return ProductBundleProductEntries.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				productBundleProductEntriesPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected ProductBundlePersistence productBundlePersistence;

	protected ProductBundleProductEntriesLocalService
		productBundleProductEntriesLocalService;

	@Reference
	protected ProductBundleProductEntriesPersistence
		productBundleProductEntriesPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}